---
version: 0
devices:
  device2:
    desc: "Device 2"
    cmds:
      status:
        desc: "Report status"
        uses:
          - module: dummy-status
            forwardArgs: true
      repeat:
        desc: "Repeat input"
        uses:
          - module: dummy-repeat
            forwardArgs: true
