---
version: 0
devices:
  device2:
    desc: "Device 2"
    cmds:
      status:
        desc: "Report status"
        modules:
          - module: dummy-status
      repeat:
        desc: "Repeat input"
        modules:
          - module: dummy-repeat
